### PR TITLE
adapter: use seata-spring-boot-starter's autoConfiguration instead of spring-cloud-alibaba-seata-starter's autoConfiguration

### PR DESCRIPTION
**Pull request by slievrly**
### Describe what this PR does / why we need it
adapter: use seata-spring-boot-starter's autoConfiguration instead of spring-cloud-alibaba-seata-starter's autoConfiguration

### Describe how you did it
adapter: use seata-spring-boot-starter's autoConfiguration instead of spring-cloud-alibaba-seata-starter's autoConfiguration
1. remove GlobalTransactionAutoConfiguration、SeataProperties
2. use seata-springboot-starter instead of seata-all
3. use application.properties instead of *.conf
4. use auto proxy datasource instead of DataSourceProxy
5. compatible with previous configuration in spring-cloud-alibaba-seata  ref https://github.com/seata/seata/blob/677d4426454929071100931f7ffb8fd054c0bdbd/seata-spring-boot-starter/src/main/java/io/seata/spring/boot/autoconfigure/properties/SeataProperties.java#L46

### Describe how to verify it
run seata's sample

### CODE REVIEW

**Comment by fangjian0423** [comment]
Is it compatible with two spring boot versions?

**Comment by slievrly** [comment]
> Is it compatible with two spring boot versions?

@xingfudeshi

**Comment by xingfudeshi** [comment]
I will fix these known problems as below:
1.In file mode, disableTransaction does not take effect.
2.Do the Spring cloud compatibility testings.

**Comment by xingfudeshi** [comment]
seata-spring-boot-starter is based on spring boot 1.5.22.RELEASE (it is the latest version of the current spring boot1.X version), and it has been tested in 1.5.22 and 2.1.4.RELEASE versions.@fangjian0423 @fangjian0423

**Comment by fangjian0423** [comment]
> seata-spring-boot-starter is based on spring boot 1.5.22.RELEASE (it is the latest version of the current spring boot1.X version), and it has been tested in 1.5.22 and 2.1.4.RELEASE versions.@fangjian0423 @fangjian0423

could you test it in Spring Boot 2.x? The next version of s-c-alibaba based on Spring Boot 2.x

**Comment by xingfudeshi** [comment]
> > seata-spring-boot-starter is based on spring boot 1.5.22.RELEASE (it is the latest version of the current spring boot1.X version), and it has been tested in 1.5.22 and 2.1.4.RELEASE versions.@fangjian0423 @fangjian0423
> 
> could you test it in Spring Boot 2.x? The next version of s-c-alibaba based on Spring Boot 2.x

Testing has passed base on spring boot 2.0.9.RELEASE and 2.0.0.RELEASE

**Comment by xingfudeshi** [comment]
@fangjian0423

**Pull request merged**
