### PR TITLE
optimize pom.xml, upgrade dubboversion

### PR DESCRIPTION
**Pull request by tswstarplanet**
### Does this pull request fix one issue?

#857

### CODE REVIEW

**Comment by fangjian0423** [comment]
Hi, could you please [sign the CLA](https://cla-assistant.io/alibaba/spring-cloud-alibaba?pullRequest=858)?

**Comment by tswstarplanet** [comment]
> Hi, could you please [sign the CLA](https://cla-assistant.io/alibaba/spring-cloud-alibaba?pullRequest=858)?

I click the link, and it display that I have signed the CLA. In fact, I am a contributor of seata, I have signed CLA of alibaba. Is that some problems about that ?

**Comment by fangjian0423** [comment]
image

It seems you use wrong github id.

**Comment by tswstarplanet** [comment]
> image
> 
> It seems you use wrong github id.

It maybe not. I have only one github id. I can submit to seata now.

**Comment by fangjian0423** [comment]
you have only one github id, but you don't configure it in your local or configure not correct.

add github id in `.git/config` like this:

```
[user]
  name = githubid
  email = githubemail
```

or modify it with `git config ...`

**Comment by tswstarplanet** [comment]
alibaba-cla
@fangjian0423 I have signed

**Comment by tswstarplanet** [comment]
Ok, I will try to configure it.

**Comment by fangjian0423** [comment]
After you configure it correct, maybe you should create a new pr.

**Comment by tswstarplanet** [comment]
alibaba-cla-commit

@fangjian0423 I have a look at the git log, the author is my github id

**Comment by tswstarplanet** [comment]
It's ok, it's because I remove the email address from my github email settings.

**Comment by tswstarplanet** [comment]
I find the pr have some problems, let me solve them.

**Comment by fangjian0423** [comment]
i think you could create a new pr to optimize the version in all poms.

circleci build error now.

**Comment by tswstarplanet** [comment]
> i think you could create a new pr to optimize the version in all poms.
> 
> circleci build error now.

But I use commit --amend. It seems difficult to back.
I use revision to replace all version constants. It can install successfully in my computer. Is there some configurations to be set ?

**Pull request closed without merging**
