### PR TITLE
Updated all dependencies to the latest versions

### PR DESCRIPTION
**Pull request by vishalsingh2972**

### CODE REVIEW

**Comment by yuluo-yx** [comment]
Did you run tests on all example projects?

**Comment by vishalsingh2972** [comment]
> Did you run tests on all example projects?
> 

Yes

**Comment by vishalsingh2972** [comment]
> Did you run tests on all example projects?

yes, could you please review and check if everything is working fine and merge the PR or suggest any corrections if required @ruansheng8 @steverao @flystar32

**Comment by ruansheng8** [comment]
@vishalsingh2972 
The most of dependencies in the project are managed through `dependencyManagement` eliminating the need for manually specifying the precise version number for each dependency.

See [`spring-cloud-alibaba/pom.xml`](https://github.com/alibaba/spring-cloud-alibaba/blob/2022.x/pom.xml):  

```xml

    <dependencyManagement>
        <dependencies>

            <!-- Spring Dependencies -->
            <dependency>
                <groupId>org.springframework.boot</groupId>
                <artifactId>spring-boot-dependencies</artifactId>
                <version>${spring-boot.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.springframework.cloud</groupId>
                <artifactId>spring-cloud-dependencies</artifactId>
                <version>${spring.cloud.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>com.alibaba.cloud</groupId>
                <artifactId>spring-cloud-alibaba-dependencies</artifactId>
                <version>${project.version}</version>
                <type>pom</type>
                <scope>import</scope>
            </dependency>

            <dependency>
                <groupId>org.apache.rocketmq</groupId>
                <artifactId>rocketmq-client</artifactId>
                <version>${rocketmq.version}</version>
            </dependency>
            <dependency>
                <groupId>org.apache.rocketmq</groupId>
                <artifactId>rocketmq-acl</artifactId>
                <version>${rocketmq.version}</version>
            </dependency>

        </dependencies>
    </dependencyManagement>

```

**Pull request closed without merging**
