### PR TITLE
minior improvements for nacos doc, examples code

### PR DESCRIPTION
**Pull request by Roger3581321**
explicitly use standalone mode in windows otherwise throwing exceptions

### Describe what this PR does / why we need it
explicitly use standalone mode otherwise cluster mode(default mode) in windows batch environment. If it goes into cluster mode, it will encounter exceptions.

### Does this pull request fix one issue?
no

### Describe how you did it
add -m option and standalone parameter

### Describe how to verify it
I followed the steps and verified it by using nacos

### CODE REVIEW

**Comment by yuhuangbin** [comment]
The default mode is `standalone`.

**Comment by Roger3581321** [comment]
Hello yuhuanbin,
In the latest release nacos 1.3.2（Aug 4, 2020）, the default mode is cluster mode, resulting in exceptions. Please have a look at the snapshot.
snapshot

**Comment by Roger3581321** [comment]
Hello all, 
I have improved these minior points and please take a look: 
1 explicitly add nacos service discovery option
It is intended to tell developers that there is an option spring.cloud.nacos.discovery.enabled to enable or disable the service discovery function as described in the spring cloud official document.

2 handle divide zero case 
As for @GetMapping("/divide"), I have handled b = 0 case(divisor), otherwise there will be an exception.

**Comment by Roger3581321** [comment]
> The default mode is `standalone`.

Dear yuhuanbin,
    Please kindly have a look at my reply and snapshot.

**Comment by Roger3581321** [comment]
Hello @fangjian0423, 
    Please kindly have a look at these minior improvements for nacos doc, examples code.

**Comment by zkzlx** [comment]
LGTM

**Pull request merged**
