### PR TITLE
Fix nacos config namespace

### PR DESCRIPTION
**Pull request by ruansheng8**
### Describe what this PR does / why we need it
when using `spring.cloud.nacos.config.namespace=public`  , set 'public' to ''

### Does this pull request fix one issue?
refer #2872 #2869

### CODE REVIEW

**Comment by steverao** [comment]
Why don't solve it in `com.alibaba.cloud.nacos.NacosConfigProperties#assembleConfigServiceProperties` directly?

**Comment by ruansheng8** [comment]
> Why don't solve it in `com.alibaba.cloud.nacos.NacosConfigProperties#assembleConfigServiceProperties` directly?

Ok , i fixed it in NacosConfigProperties

**Comment by steverao** [comment]
LGTM.

**Comment by steverao** [comment]
Please create a same PR to branch of 2.2.x.

**Pull request merged**
