### PR TITLE
[2022.x] Add SentinelProtectInterceptor AOT hints

### PR DESCRIPTION
**Pull request by ruansheng8**
### Describe what this PR does / why we need it

```java
mvn clean native:compile -Pnative
```

### CODE REVIEW

**Comment by ruansheng8** [comment]
也可以通过以下方式来查看是否正确生成相关的配置文件:
1.  `mvn compile`
2. `mvn spring-boot:process-aot -Pnative -Dstart-class=com.alibaba.cloud.examples.RestTemplateApplication`
3. 查看文件`/target/spring-aot/main/resources/META-INF/native-image/com.alibaba.cloud/sentinel-resttemplate-example/reflect-config.json` 可以看到对应的配置: 
```json
  {
    "name": "com.alibaba.cloud.sentinel.custom.SentinelProtectInterceptor",
    "methods": [
      {
        "name": "<init>",
        "parameterTypes": [
          "com.alibaba.cloud.sentinel.annotation.SentinelRestTemplate",
          "org.springframework.web.client.RestTemplate"
        ]
      }
    ]
  }
```

**Review by steverao — COMMENTED** [review]
You should add this PR to module of `spring-cloud-starter-alibaba-sentinel`.

**Comment by ruansheng8** [comment]
@steverao 改了一个版本，如果没有问题的话，后续其他模块就按照这种方式进行调整

**Comment by yuluo-yx** [comment]
@ruansheng8  I tested it locally and it works fine in my environment.

**Review by steverao — APPROVED** [review]
LGTM, thanks @ruansheng8

**Pull request merged**
