### PR TITLE
Update GlobalTransactionAutoConfiguration.java

### PR DESCRIPTION
**Pull request by sundong1982**
applicationName + "-fescar-service-group" 改为 applicationName + "-seata-service-group"

### CODE REVIEW

**Comment by sundong1982** [comment]
#801

**Comment by fangjian0423** [comment]
Hi, could you please [sign the CLA](https://cla-assistant.io/alibaba/spring-cloud-alibaba?pullRequest=802)?

**Comment by fangjian0423** [comment]
could you pls modify `fescar` to `seata` in seata-module like https://github.com/alibaba/spring-cloud-alibaba/blob/master/spring-cloud-alibaba-seata/src/main/java/com/alibaba/cloud/seata/feign/SeataFeignClient.java#L71.

**Comment by sundong1982** [comment]
@fangjian0423 #804

**Pull request closed without merging**
