### PR TITLE
Fix issue 2503: remove the redundant log

### LINKED ISSUE #2503: 2021.0.1 use rockentMq 4.9.2 logger bug
**Which Component**
spring-cloud-stream 3.1.6，spring cloud alibaba 2021.0.1

**Describe the bug**
1、class RocketMQProducerMessageHandler The log is printed every time a message is sent

`package com.alibaba.cloud.stream.binder.rocketmq.integration.outbound;`

`log.info("the message has sent,message={},sendResult={}", mqMessage,sendResult);`

The info level modifies the debug level 
`log.debug("the message has sent,message={},sendResult={}", mqMessage,sendResult);`

2、class DirectWithAttributesChannel print 
`2022-04-07 00:17:02.062  INFO 10844 --- [   scheduling-1] o.s.c.s.m.DirectWithAttributesChannel    : Channel 'unknown.channel.name' has 1 subscriber(s).`

### PR DESCRIPTION
**Pull request by pandaapo**
### Describe what this PR does / why we need it
Remove the redundant log.

### Does this pull request fix one issue?
Fixes #2503

### CODE REVIEW

**Review by steverao — APPROVED** [review]

**Comment by steverao** [comment]
Please modify according to the prompts.

**Comment by pandaapo** [comment]
> Please modify according to the prompts.

I'm sorry. I'm not sure what's your meaning. Where are the prompts? I can't find them out.
捕获

**Comment by Cyoking** [comment]
nice

**Comment by steverao** [comment]
> > Please modify according to the prompts.
> 
> I'm sorry. I'm not sure what's your meaning. Where are the prompts? I can't find them out. 捕获

You see the code how to solve the problem in branch of 2021.x. Please use debug log instead of deleting it.

**Comment by pandaapo** [comment]
> You see the code how to solve the problem in branch of 2021.x. Please use debug log instead of deleting it. 

I delete `log.info` because there has been `log.debug` below.
捕获

**Comment by steverao** [comment]
> > You see the code how to solve the problem in branch of 2021.x. Please use debug log instead of deleting it.
> 
> I delete `log.info` because there has been `log.debug` below. 捕获

alright, sorry, I didn't see the code below before.

**Pull request merged**
