### PR TITLE
Updating readme-zh.md

### PR DESCRIPTION
**Pull request by Roger3581321**
### Describe what this PR does / why we need it
Updating the readme 

### Does this pull request fix one issue?
No

### Describe how you did it
Added more descriptions, fixed a few typos and added one new configuration line

### Describe how to verify it
Checked the readme

### Special notes for reviews
None

### CODE REVIEW

**Comment by steverao** [comment]
Please modify the readme.md too, thanks!

**Comment by Roger3581321** [comment]
> None

> Please modify the readme.md too, thanks!
Ok, I have updated the readme.md in PR#2394. Please have a look.

**Comment by Roger3581321** [comment]
> 
Ok, I have updated the readme.md in PR#2394. Please have a look.

**Comment by Roger3581321** [comment]
> Please modify the readme.md too, thanks!
Ok, I have updated the readme.md in PR#2394. Please have a look.

**Comment by Roger3581321** [comment]
> Please modify the readme.md too, thanks!

Ok, I have updated the readme.md in PR#2394. Please have a look.

**Pull request merged**
