### PR TITLE
Modify end of line comments, SimpleDateFormat >> LocalDateTime

### PR DESCRIPTION
**Pull request by cheneychoi**
修改行尾注释，去除不必要的异常抛出，修改SimpleDateFormat为LocalDateTime。

### CODE REVIEW

**Comment by fangjian0423** [comment]
Hi, could you please [sign the CLA](https://cla-assistant.io/alibaba/spring-cloud-alibaba?pullRequest=1161)?

**Comment by cheneychoi** [comment]
> Hi, could you please [sign the CLA](https://cla-assistant.io/alibaba/spring-cloud-alibaba?pullRequest=1161)?
Already signed

**Comment by fangjian0423** [comment]
It seems your email is not bound with Github.

image

**Comment by cheneychoi** [comment]
> It seems your email is not bound with Github.
> 
> image

seems good now

**Comment by fangjian0423** [comment]
> license/cla Pending — Contributor License Agreement is not signed yet.

please [sign the CLA](https://cla-assistant.io/alibaba/spring-cloud-alibaba?pullRequest=1161) , thanks.

**Comment by cheneychoi** [comment]
> > license/cla Pending — Contributor License Agreement is not signed yet.
> 
> please [sign the CLA](https://cla-assistant.io/alibaba/spring-cloud-alibaba?pullRequest=1161) , thanks.

image
It seems i have signed

**Comment by fangjian0423** [comment]
hey, you commit with two Github ids and only one of them has been signed.

image

**Comment by cheneychoi** [comment]
> 嗨，您提交了两个Github ID，但其中只有一个已签名。
> 
> 图片
id 'cheney' was my mistake, and it has been fixed later

**Pull request closed without merging**
