### PR TITLE
Fixed: #2018 #2150 #1343 解决跨组共享服务注册及调用

### LINKED ISSUE #2018: how to share default service
**Which Component**
Nacos Discovery

I want to register a default group service  and share with other group service.  If no this feature, each of us need to start up too many IDE and service, but I just need to care for my code.

### PR DESCRIPTION
**Pull request by on36**
### Describe what this PR does / why we need it
解决跨组共享服务注册及跨组服务调用

### Does this pull request fix one issue?

Fixes: #2018 #2150 #1343

### CODE REVIEW

**Comment by steverao** [comment]
We had a discussion about this PR in tonight community meeting, someone though it's neccessary, but others didn't think so! 
1. For a framework, we need to have some rules that can help users avoid to make mistakes. If some users need it, maybe they can do it by themselves. 
2. We can provider the feature and set it default close.
Welcome everyone leave your opinion in this PR below：）

**Comment by on36** [comment]
同一个环境下面存在不同业务线这种场景应该很多，既需要业务隔离，又需要公共业务功能(如组织人员，图片附件，订单，支付)能够共用，在微服务模式下，差不多就是这样的需要，如果调用的公共服务部署两套，这个既浪费资源又增加额外维护，我们使用场景中相当常见

**Comment by galaxy-sea** [comment]
> 同样一个环境下面存在不同业务线的这种情况（很多，既需要业务隔离，又需要公共功能组织人员，图片附件，订单，支付）使用，在微服务模式下，需要差不多的这样的业务能力，如果增加调用的公共服务部署两套，这既浪费资源又额外维护，我们使用场景中相当频繁

你其实可以考虑用[sidecar](https://github.com/alibaba/spring-cloud-alibaba/tree/2021.x/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-sidecar)组件来解决你跨group调用的问题，这样子也符合nacos的group隔离策略

**Comment by steverao** [comment]
By community discussion, we don't plan to provide relevant function in community now and close first. Thank you for your support.

**Pull request closed without merging**
