### PR TITLE
Docs: Add example: nacos config setting Group

### PR DESCRIPTION
**Pull request by yuyu1025**
### Describe what this PR does / why we need it
The current nacos config example is missing the group setting. It's actually in the code, so it would be helpful to have a more complete example.

### Does this pull request fix one issue?
No

### Describe how you did it
I tracked down the logic for the nacos processing by reading the spring code for config.implant processing, which can be found in the following code.
/com/alibaba/cloud/nacos/configdata/NacosConfigDataLocationResolver:170   

Translated with DeepL.com (free version)

### CODE REVIEW

**Review by ruansheng8 — APPROVED** [review]

**Review by yuluo-yx — COMMENTED** [review]
Pls update en doc.

**Comment by yuyu1025** [comment]
> Pls update en doc.

OK

**Review by yuluo-yx — APPROVED** [review]
LGTM.

**Comment by ruansheng8** [comment]
LGTM

**Pull request merged**
