### PR TITLE
【WIP】Add maven-checkstyle-plugin to check code style

### PR DESCRIPTION
**Pull request by zhaoyuguang**
### Describe what this PR does / why we need it
Add maven-checkstyle-plugin to check code style
My local repo test: https://github.com/zhaoyuguang/spring-cloud-alibaba/pull/2

### Does this pull request fix one issue?
https://github.com/alibaba/spring-cloud-alibaba/issues/935

### CODE REVIEW

**Comment by fangjian0423** [comment]
It seems don't refer https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/spring-cloud-dependencies-parent/eclipse-code-formatter.xml.

**Comment by zhaoyuguang** [comment]
> It seems don't refer https://raw.githubusercontent.com/spring-cloud/spring-cloud-build/master/spring-cloud-dependencies-parent/eclipse-code-formatter.xml.

Yes, At the moment, I just want to make `mvn checkstyle` work. There is a useless import in our code, but it seems that CI has passed.

**Comment by zhaoyuguang** [comment]
@fangjian0423 Hi, I can't find a correct way to finish this, such as
`<setting id="org.eclipse.jdt.core.formatter.insert_space_after_ellipsis" value="insert"/>`
at https://checkstyle.sourceforge.io/config_whitespace.html#NoWhitespaceAfter, there has no rule for `insert_space_after_ellipsis`

**Comment by fangjian0423** [comment]
resolved.

**Pull request closed without merging**
