### PR TITLE
Change NacosServiceManager injection mode to constructor injection

### LINKED ISSUE #2271: NacosServiceRegistry类里引用NacosServiceManager的方式问题
版本：2.2.6
https://github.com/alibaba/spring-cloud-alibaba/blob/387dd46fa4d037dad3d7091fca2274d4cc1d5034/spring-cloud-alibaba-starters/spring-cloud-starter-alibaba-nacos-discovery/src/main/java/com/alibaba/cloud/nacos/registry/NacosServiceRegistry.java#L40-L60

在NacosServiceRegistry里引用NacosServiceManager是采用直接注入的方式，当在我想在项目中实现注册多个Nacos注册中心时，就没办法复用此类，建议引用NacosServiceManager的方式和引用NacosDiscoveryProperties保持一致，都通过构造函数引入:

From Google Translate:
NacosServiceManager is referenced in NacosServiceRegistry by direct injection. When I want to register multiple Nacos registries in the project, there is no way to reuse this type. It is recommended that the method of referencing NacosServiceManager and referencing NacosDiscoveryProperties are consistent, both through construction Function introduction:

```java
    private final NacosDiscoveryProperties nacosDiscoveryProperties;

    private final NacosServiceManager nacosServiceManager;

    public NacosServiceRegistry(NacosServiceManager nacosServiceManager, NacosDiscoveryProperties nacosDiscoveryProperties) {
        this.nacosServiceManager = nacosServiceManager;
        this.nacosDiscoveryProperties = nacosDiscoveryProperties;
    }
```

### PR DESCRIPTION
**Pull request by misselvexu**
### Describe what this PR does / why we need it
Change NacosServiceManager injection mode to constructor injection

### Does this pull request fix one issue?

Fix #2271

### CODE REVIEW

**Comment by steverao** [comment]
Please keep the formatting of the code consistent！

**Comment by misselvexu** [comment]
> Please keep the formatting of the code consistent！

okay .

**Comment by steverao** [comment]
> > Please keep the formatting of the code consistent！
> 
> okay .

By the way, you need to sign the Contributor License Agreement before merging the code.

**Comment by steverao** [comment]
You just need to format the codes that you modified and keep the code style consistent with ours, such as the number of spaces

**Comment by misselvexu** [comment]
> You just need to format the codes that you modified and keep the code style consistent with ours, such as the number of spaces

Already formatted .

**Comment by steverao** [comment]
LGTM.

**Pull request merged**
