### PR TITLE
Fix: update nacosWatch doc

### PR DESCRIPTION
**Pull request by ruansheng8**
### Describe what this PR does / why we need it
Update nacosWatch doc

### Does this pull request fix one issue?

Related issue #2868

### CODE REVIEW

**Review by steverao — APPROVED** [review]

**Comment by steverao** [comment]
LGTM, thanks @ruansheng8

**Review by yuhuangbin — APPROVED** [review]

**Comment by steverao** [comment]
Don't forget to create a same PR to branch of 2.2.x.

**Comment by ruansheng8** [comment]
> Don't forget to create a same PR to branch of 2.2.x.

This commit is already included in #2904

**Comment by steverao** [comment]
> > Don't forget to create a same PR to branch of 2.2.x.
> 
> This commit is already included in #2904

Great!

**Pull request merged**
