### PR TITLE
[docs] add bootstrap dependies

### PR DESCRIPTION
**Pull request by kaori-seasons**
### Describe what this PR does / why we need it
Related to [issue-4219](https://github.com/alibaba/spring-cloud-alibaba/issues/2419)

### CODE REVIEW

**Comment by ralf0131** [comment]
Could you also update the english version under `spring-cloud-alibaba-docs/src/main/asciidoc/nacos-config.adoc` ?

**Comment by complone** [comment]
ok i will finish it asap

**Comment by complone** [comment]
> 你也可以更新下英文版本`spring-cloud-alibaba-docs/src/main/asciidoc/nacos-config.adoc`吗？

ok i will finish it asap

**Comment by kaori-seasons** [comment]
> 你也可以更新下英文版本`spring-cloud-alibaba-docs/src/main/asciidoc/nacos-config.adoc`吗？

solved

**Comment by steverao** [comment]
You need merge to 2021.x, because only the branch  of Spring Boot version > 2.4.

**Comment by kaori-seasons** [comment]
> You need merge to 2021.x, because only the branch of Spring Boot version > 2.4.

Ok, I will update the merge branch.

**Pull request merged**
