### PR TITLE
Upgrade Spring Cloud & Spring Boot version to Hoxton.SR12, 2.3.12.REL…

### LINKED ISSUE #2242: [Feature] Spring Cloud & Spring Boot version upgrede to Hoxton.SR12, 2.3.12.RELEASE

### PR DESCRIPTION
**Pull request by misselvexu**
…EASE

### Describe what this PR does / why we need it
Upgrade Spring Cloud & Spring Boot version to Hoxton.SR12, 2.3.12.RELEASE 

### Does this pull request fix one issue?

Fix #2242

### CODE REVIEW

**Comment by steverao** [comment]
Will there be compatibility issues with direct upgrades?

**Comment by misselvexu** [comment]
> Will there be compatibility issues with direct upgrades?

Let me cover all test cases again .

**Comment by steverao** [comment]
> > Will there be compatibility issues with direct upgrades?
> 
> Let me cover all test cases again .

In the past, the community used the test cases in this project(https://github.com/Nepxion/Discovery) to perform integration tests on dependency upgrades. You can find out!

**Comment by misselvexu** [comment]
> > > Will there be compatibility issues with direct upgrades?
> > 
> > 
> > Let me cover all test cases again .
> 
> In the past, the community used the test cases in this project(https://github.com/Nepxion/Discovery) to perform integration tests on dependency upgrades. You can find out!

okay .

**Comment by steverao** [comment]
I used the project's(https://github.com/Nepxion/DiscoveryGuide) test cases to finish the compatibility issues after updating the version. It's alright!

**Comment by misselvexu** [comment]
> I used the project's(https://github.com/Nepxion/DiscoveryGuide) test cases to finish the compatibility issues after updating the version. It's alright!

Okay，thanks.

**Pull request merged**
