### PR TITLE
fix(nacos): fix issue #859

### PR DESCRIPTION
**Pull request by chuntaojun**
### Does this pull request fix one issue?

fix issue #859

### CODE REVIEW

**Comment by fangjian0423** [comment]
hi, could you resolve conflicts?

**Comment by YoungL-SC** [comment]
i have checkout the code after your commit ,maybe the issue [https://github.com/alibaba/spring-cloud-alibaba/issues/859](url) has not been resolved yet.

**Comment by chuntaojun** [comment]
> i have checkout the code after your commit ,maybe the issue [https://github.com/alibaba/spring-cloud-alibaba/issues/859](url) has not been resolved yet.

I tried the ConfigService cache can be work

**Comment by chuntaojun** [comment]
> i have checkout the code after your commit ,maybe the issue [https://github.com/alibaba/spring-cloud-alibaba/issues/859](url) has not been resolved yet.

yeah，I do not consider to be clear about the spring - refresh mechanism of cloud, I raised a pr, to ensure that this problem can be solved

**Pull request merged**
