### PR TITLE
update seata version

### PR DESCRIPTION
**Pull request by yuluo-yx**
### Describe what this PR does / why we need it
update seate version to 1.6.1 in 2021.x branch

### CODE REVIEW

**Comment by steverao** [comment]
Do you run the example module to verify the compatibility?

**Comment by yuluo-yx** [comment]
> Do you run the example module to verify the compatibility?

Yes. I used NACOS with 2.2.0 locally, and the services were successfully registered and accessed the test controller, and I got the expected results. They seem to fit, at least locally in my area!

**Comment by yuluo-yx** [comment]
I got such a warning when installing dependencies
`[WARNING] The POM for com.alibaba:druid:jar:1.2.6 is invalid, transitive dependencies (if any) will not be available, enable debug logging for more details`
This should be an issue with druid, but it doesn't affect use. So I ignored the warning.

**Comment by yuluo-yx** [comment]
> Do you run the example module to verify the compatibility?

Please wait a minute, I found the problem and I'm fixing it

**Pull request closed without merging**
