### PR TITLE
[ISSUES #2357] Update Nacos to 1.4.2 in Spring Cloud Alibaba 2022.0 #2357

### LINKED ISSUE #2357: [Feature] Update Nacos to 1.4.2 in Spring Cloud Alibaba 2022.0
1.Update Nacos to 1.4.2 in Spring Cloud Alibaba 2022.0

### PR DESCRIPTION
**Pull request by lzhang131**
### Describe what this PR does / why we need it
Update Nacos to 1.4.2 in Spring Cloud Alibaba 2022.0

### Does this pull request fix one issue?
fixed #2357 

- 

> [spring-cloud-alibaba-dependencies/pom.xml]()

### CODE REVIEW

**Comment by DanielLiu1123** [comment]
It seems to have a problem with branch.

**Comment by steverao** [comment]
Please update in 2020 branch and finish necessary test.

**Comment by yuhuangbin** [comment]
Thanks for your pr~ please sign the [CLA](https://cla-assistant.io/alibaba/spring-cloud-alibaba?pullRequest=2361)

**Comment by DanielLiu1123** [comment]
Nacos will upgrade to 1.4.3 in 2022.

**Pull request closed without merging**
