### PR TITLE
Docs: deleted spring-cloud-alibaba-docs module

### PR DESCRIPTION
**Pull request by yuluo-yx**
### Describe what this PR does / why we need it

- For https://github.com/alibaba/spring-cloud-alibaba/issues/3473

### CODE REVIEW

**Review by ruansheng8 — APPROVED** [review]

**Review by ruansheng8 — COMMENTED** [review]
Edit the doc-url in the `README.md` file to the new doc-url.

**Comment by yuluo-yx** [comment]
> Edit the doc-url in the `README.md` file to the new doc-url.

yep. In order to solve this problem, I added markdown error link detection. Maybe due to repo permissions, ci is not running properly. For details, please see: https://github.com/yuluo-yx/spring-cloud-alibaba/pull/1/checks
I will check every readme file later to make sure there are no bad links.

**Review by ruansheng8 — APPROVED** [review]

**Review by chickenlj — APPROVED** [review]
LGTM.

**Comment by ruansheng8** [comment]
LGTM

**Pull request merged**
