### PR TITLE
fix EndpointId logWarning

### PR DESCRIPTION
**Pull request by lltx**
### Describe what this PR does / why we need it

image

spring cloud alibaba 2.2.3
spring boot 2.3.4

When the service starts, the above waring prompt will be thrown。

This is because the name contains illegal characters (-) when defining the name

### Does this pull request fix one issue?

NO

### Describe how you did it

The modified name does not contain illegal characters，

**Don't use camel case naming,because the official style**

### Describe how to verify it

Only need to output log at startup

### Special notes for reviews
image

image

### CODE REVIEW

**Comment by fangjian0423** [comment]
Thanks for your suggestion.

The pattern of endpoint is different in each Spring Boot version.

So i think it is no need to change the endpoint id 😄

**Comment by lltx** [comment]
spring-cloud-common   has been fixed this problem  ，this problem has been fixed, it is a BUG from Hoxton.M1

https://github.com/spring-cloud/spring-cloud-commons/issues/458


https://github.com/spring-cloud/spring-cloud-commons/commit/333779070f5b8665b6f355caebf7c7390dc2e232#diff-fb1ecc6a8824d66c496ca03ad40426cc5f9cc0e9cc04f308027a82eb7b98bff4

**Comment by lltx** [comment]
https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-2.1-Release-Notes#endpoint-id-names


```
If you have developed your own actuator @Endpoint beans you should ensure that they following the tighter naming rules introduced in Spring Boot 2.1. Specifically, IDs should be alpha-numeric only and must start with a letter (see the EndpointId class documentation for full details).

If you use - or . characters Spring Boot 2.1 will log a warning and ask you to migrate to the correct format.
```

**Review by fangjian0423 — APPROVED** [review]
LGTM

**Comment by fangjian0423** [comment]
> spring-cloud-common has been fixed this problem , it is a BUG from Hoxton.M1
> 
> [spring-cloud/spring-cloud-commons#458](https://github.com/spring-cloud/spring-cloud-commons/issues/458)
> 
> [spring-cloud/spring-cloud-commons@3337790#diff-fb1ecc6a8824d66c496ca03ad40426cc5f9cc0e9cc04f308027a82eb7b98bff4](https://github.com/spring-cloud/spring-cloud-commons/commit/333779070f5b8665b6f355caebf7c7390dc2e232#diff-fb1ecc6a8824d66c496ca03ad40426cc5f9cc0e9cc04f308027a82eb7b98bff4)
> 
> @fangjian0423

Thanks for your remind.

**Pull request merged**
