### PR TITLE
update copyright in 2022.x

### PR DESCRIPTION
**Pull request by yuluo-yx**
update copyright

### CODE REVIEW

**Comment by steverao** [comment]
There are some files missing to modify? There are some time of files is 2013-2019, such as module of `spring-cloud-alibaba-commons`. Please check again carefully!

**Comment by yuluo-yx** [comment]
> There are some files missing to modify? There are some time of files is 2013-2019, such as module of `spring-cloud-alibaba-commons`. Please check again carefully!

ok!

**Comment by steverao** [comment]
> > There are some files missing to modify? There are some time of files is 2013-2019, such as module of `spring-cloud-alibaba-commons`. Please check again carefully!
> 
> ok!

There are still same problem mentioned above. Please check carefully, such as `rocketmq-examples`.

**Review by steverao — APPROVED** [review]
LGTM, thanks @yuluo-yx

**Comment by leafxt** [comment]
/**
	 * Delete configuration.
	 *
	 * @param dataId dataId
	 * @param group group
	 * @return boolean
	 */
	@RequestMapping("/remoteConfig")
	public boolean remoteConfig(@RequestParam("dataId") String dataId,
			@RequestParam(value = "group", required = false) String group)
			throws NacosException {
		if (StringUtils.isEmpty(group)) {
			group = DEFAULT_GROUP;
		}
		ConfigService configService = nacosConfigManager.getConfigService();
		return configService.removeConfig(dataId, group);
	}
	



The function name cannot express the intention of deleting the configuration. "Did you misspell 'remove' as 'remote'?"

**Comment by steverao** [comment]
> /** * Delete configuration. * * @param dataId dataId * @param group group * @return boolean */ @RequestMapping("/remoteConfig") public boolean remoteConfig(@RequestParam("dataId") String dataId, @RequestParam(value = "group", required = false) String group) throws NacosException { if (StringUtils.isEmpty(group)) { group = DEFAULT_GROUP; } ConfigService configService = nacosConfigManager.getConfigService(); return configService.removeConfig(dataId, group); }
> 
> The function name cannot express the intention of deleting the configuration. "Did you misspell 'remove' as 'remote'?"

Yes, welcome to create relevant PR to fix it.

**Pull request merged**
