### PR TITLE
Correct spelling mistakes in readme.md

### PR DESCRIPTION
**Pull request by Cyoking**
Describe what this PR does / why we need it
misspelling in readme file

Describe how you did it
Correct spelling mistakes in readme.md

### CODE REVIEW

**Review by Cyoking — COMMENTED** [review]
I have read it, no problem

**Review by cevencheng — APPROVED** [review]

**Comment by steverao** [comment]
Please create a same PR to branch of 2021.x.

**Review by steverao — APPROVED** [review]

**Comment by steverao** [comment]
By the way, please sign the [Contributor License Agreement](https://cla-assistant.io/alibaba/spring-cloud-alibaba?pullRequest=2771).

**Comment by Cyoking** [comment]
> 

I have signed the CLA
image

**Pull request closed without merging**
