### PR TITLE
add preferredIPversion to resolve ipv4/ipv6  address or both

### PR DESCRIPTION
**Pull request by cheese8**
### Describe what this PR does / why we need it
add preferredIPversion to register for your service instance with ipv4, ipv6 or both.

### Does this pull request fix one issue?

Ref #2593

### Describe how you did it
As coded, get ipv4 while v4 preferred, get ipv6 while v6 preferred, return ip with `IPV4,IPV6` if both preferred and register for your service instance twice later.

And how about to enhance org.springframework.cloud.commons.util.InetUtils with ipv6?  @ralf0131 

### Describe how to verify it
not verified yet.

### Special notes for reviews
NONE

### CODE REVIEW

**Comment by steverao** [comment]
You just think about resolving IPv6 address, you don't care RPC invocation. When you get IPv6 address from registry, if use IPv6 to create a request just like IPv4, maybe it will get error.

**Comment by steverao** [comment]
You just think about resolving IPv6 address, you don't care RPC invocation. When you get IPv6 address from registry, if use IPv6 to create a request just like IPv4, maybe it will get error.

**Comment by cheese8** [comment]
> You just think about resolving IPv6 address, you don't care RPC invocation. When you get IPv6 address from registry, if use IPv6 to create a request just like IPv4, maybe it will get error.

ok, thanks for your  reminder, I will test it later. This pr is planed to resolving the IPv6 address, I changed the pr title.

**Comment by steverao** [comment]
#2628

**Pull request closed without merging**
